### ISSUE TITLE
Cannot find module 'moment'.

### ISSUE THREAD

**Issue by zexliu** [ArcherTrister/ant-design-pro-vue-ts#1]
typescript 初学者 尝试运行该项目

以下是错误信息 是我环境的问题吗?

ERROR in /Users/zex/workspace/web/ant-design-pro-vue-ts/src/views/list/TableList.vue(135,20):
135:20 Cannot find module 'moment'.
    133 | <script lang="ts">
    134 | import { Component, Vue } from 'vue-property-decorator'
  > 135 | import moment from 'moment'
        |                    ^
    136 | import { STable, Ellipsis } from '@/components'
    137 | import StepByStepModal from './modules/StepByStepModal.vue'
    138 | import CreateForm from './modules/CreateForm.vue'
ERROR in /Users/zex/workspace/web/ant-design-pro-vue-ts/src/views/personal/center/page/Project.vue(35,20):
35:20 Cannot find module 'moment'.
    33 | <script lang="ts">
    34 | import { Component, Vue } from 'vue-property-decorator'
  > 35 | import moment from 'moment'
       |                    ^
    36 | import { TagSelect, TagSelectOption, StandardFormRow, Ellipsis, AvatarList, AvatarListItem } from '@/components'
    37 | 
    38 | @Component({
Version: typescript 3.5.3

**Comment by ArcherTrister** [comment]
初步判断是包还原失败，建议手动执行npm i moment -S 或者 yarn add moment

**Comment by ArcherTrister** [comment]
> 打字稿初学者尝试运行该项目
> 
> 以下是错误信息是我环境的问题吗？
> 
> /Users/zex/workspace/web/ant-design-pro-vue-ts/src/views/list/TableList.vue(135,20）中的错误：
> 135：20找不到模块'moment'。
> 133 | <script lang =“ ts”>
> 134 | 从'vue-property-decorator'导入{Component，Vue}
> 
> > 135 | 从“瞬间”导入瞬间
> > | ^ 
> > 136 | 从“ @ / components”中导入{稳定，省略号} 
> > 137 | 从'./modules/StepByStepModal.vue'138导入StepByStepModal 
> > 。从/Users/zex/workspace/web/ant-design-pro-vue-ts/src/views/personal/center/page/Project.vue（35,20）
> > 中的'./modules/CreateForm.vue' 错误导入CreateForm ）：
> > 35 : 20找不到模块'moment'。
> > 33 | <script lang =“ ts”> 
> > 34 | 从“ vue-property-decorator” 
> > 35 导入{Component，Vue} 从“瞬间”导入瞬间
> > | ^ 
> > 36 | 从'@ / components'导入{TagSelect，TagSelectOption，StandardFormRow，省略号，AvatarList，AvatarListItem} 
> > 37 | 
> > 38 | @零件（{ 
> > 版本：打字稿3.5.3

初步判断是包还原失败，建议手动执行

**Comment by ArcherTrister** [comment]
> 打字稿初学者尝试运行该项目
> 
> 以下是错误信息是我环境的问题吗？
> 
> /Users/zex/workspace/web/ant-design-pro-vue-ts/src/views/list/TableList.vue(135,20）中的错误：
> 135：20找不到模块'moment'。
> 133 | <script lang =“ ts”>
> 134 | 从'vue-property-decorator'导入{Component，Vue}
> 
> > 135 | 从“瞬间”导入瞬间
> > | ^ 
> > 136 | 从“ @ / components”中导入{稳定，省略号} 
> > 137 | 从'./modules/StepByStepModal.vue'138导入StepByStepModal 
> > 。从/Users/zex/workspace/web/ant-design-pro-vue-ts/src/views/personal/center/page/Project.vue（35,20）
> > 中的'./modules/CreateForm.vue' 错误导入CreateForm ）：
> > 35 : 20找不到模块'moment'。
> > 33 | <script lang =“ ts”> 
> > 34 | 从“ vue-property-decorator” 
> > 35 导入{Component，Vue} 从“瞬间”导入瞬间
> > | ^ 
> > 36 | 从'@ / components'导入{TagSelect，TagSelectOption，StandardFormRow，省略号，AvatarList，AvatarListItem} 
> > 37 | 
> > 38 | @零件（{ 
> > 版本：打字稿3.5.3

初步判断是包还原失败，建议手动执行 npm i moment -S 或 yarn add moment
